### ISSUE TITLE
 IIS  is locking DD4T.Providers.Tridion9.1.CIL.dll  and Autodeployment failed as it is not able to delete this particular dll

### ISSUE THREAD

**Issue by mahesh428** [dd4t/DD4T.Providers.Tridion9.1.CIL#3]
Autodeployment tool not able to delete DD4T.Providers.Tridion9.1.CIL.dll because of it is used by w3wp.exe process(IIS process).

Please let us know what can be done to fix this issue.

We are using SDL 9.1.

Devops don't want to do App pool stop during auto deployment process.

**Comment by quirijnslings** [comment]
I doubt if this is an issue we can solve. It has to do with how IIS is working in your environment. Normally, when you run a site, IIS copies all DLLs from the bin folder to C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files. This is why you can normally replace DLLs in the bin folder while a site is running.
There may be situations when this is not happening. See https://stackoverflow.com/questions/49660923/why-is-iis-worker-process-locking-a-file for one such situation (but there may be more).

By the way, if you change a DLL in the bin folder, the application pool is probably recycled anyway.

**Comment by quirijnslings** [comment]
@mahesh428 can you let us know if this is still a problem? Otherwise, I will close this issue.

**Comment by mahesh428** [comment]
@quirijnslings - I have tried following option as well and still facing the issue and not facing any issue with DD4T.Providers.Tridion8.CIL.dll

I have verified my current project history and found out that this issue happened with DD4T.Providers.Tridion8.CIL.dll---2.2.0 version as well and it was resolved after making updates to 2.2.2

Can you please verify whether same fix is present in  following or not.

**Comment by mahesh428** [comment]
@quirijnslings -Another observation we made between 
DD4T.Providers.Tridion8.CIL.dll---2.2.0 and  2.2.2 nuget packages is all dependency libraries are present directly 2.2.2 version.
![image](https://user-images.githubusercontent.com/15623579/81734655-72f6d280-9459-11ea-8299-3fa813a84e5c.png)

**Comment by quirijnslings** [comment]
This is unrelated, right? Also, this was reported earlier and solved, see https://github.com/dd4t/DD4T.Providers.SDLWeb8.5.CIL/issues/5.

**Comment by quirijnslings** [comment]
I tried to reproduce. I did notice that occasionally the DLL gets locked, but if I retry after a few seconds, I can remove the DLL again. What might also help, is to rename it first and then remove it.

**Comment by mahesh428** [comment]
Code is deployed using Teamcity Auto deployment process. Because of following error the process is breaking and devops team has to go manually and fix the issue.

We are not observing following issue with dd4t/DD4T.Providers.SDLWeb8.CIL.Could you please verify is there anyway issue can be fixed.

Are you able to find the root cause of the issue.what process is locking IIS worker process.

**Comment by quirijnslings** [comment]
I found the problem. It is actually not in the provider itself but in the DD4T.DI.* projects. I have created separate issues to resolve this:

- https://github.com/dd4t/DD4T.DI.Autofac/issues/23
- https://github.com/dd4t/DD4T.DI.Unity/issues/13
- https://github.com/dd4t/DD4T.DI.SimpleInjector/issues/2
- https://github.com/dd4t/DD4T.DI.Ninject/issues/14

If you're using Autofac, you can try it out now, by upgrading the DD4T.DI.Autofac package to 2.5.69-alpha.

**Comment by mahesh428** [comment]
@quirijnslings -Thanks a lot for finding the fix.Currently we are testing the same and will update you with the results

**Comment by mahesh428** [comment]
@quirijnslings -You can close the following bug.Thanks for all the help.

**Comment by quirijnslings** [comment]
You're welcome. We will fix the issues in all 4 providers and close those tickets too. When that is done, you can switch to a new release of DD4T.DI.Autofac, probably 2.5.1
